### ISSUE TITLE
Reddit Endless Blocking/Refresh Loop in uBlock Origin

### ISSUE THREAD

**Issue by AlmightyHeretic** [acnapyx/paywall-remover#4]
I am unable to read or scroll reddit posts while Paywall Remover is enabled in uBlock Origin. It looks like the page is just refreshing constantly and the block counter keeps ticking up indefinitely.

**Comment by acnapyx** [comment]
This is probably related to Reddit injecting promoted posts. Can you provide more details which of the two lists are you using - paywall-remover-list, or paywall-remover-mini? Also, since when this started happening? 

Asking this because I've recently integrated an external list that was contributed anonymously, and if it breaks things, it'd be better probably to split it into a separate one so users can load it as an individual list. (I haven't tested it in detail so I cannot vouch for its functionality.)

**Comment by AlmightyHeretic** [comment]
I'm using paywall-remover-list. I only started noticing the issue maybe two weeks ago.

**Comment by AlmightyHeretic** [comment]
![Screenshot from 2022-03-04 14-09-37](https://user-images.githubusercontent.com/62065336/156834744-22c8d374-b08d-4c78-b60b-b0c15ef79192.png)
I don't know if it helps but here's a screenshot of the blocked queries in uBO's logger.

**Comment by andrewhansen86** [comment]
I discovered this same issue this morning. Thought it was a chrome update that was causing it so I just waited for the next chrome update thinking it would fix it. This morning I dug into it and was able to narrow it down to this. It had been happening for about the last 1-2 weeks for me.

**Comment by acnapyx** [comment]
Rolled back to previous version of the list, without the anonymous contribution. Should fix stuff for now.

**Comment by AlmightyHeretic** [comment]
Just updated lists and checked again. Seems to be working well now. Funny thing is, it was also blocking Threema from successfully connecting to my phone and I didn't realize it. Thanks!
